---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure DNSMasq
  license: MIT
  min_ansible_version: "2.8"
  role_name: ansible_dnsmasq
  namespace: mrlesmithjr

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - system
dependencies: []
