---
- name: drink systemd koolaid
  apt:
    name: "{{ systemd_koolaid_packages }}"
    state: present
  vars:
    systemd_koolaid_packages:
      - systemd-timesyncd
      - systemd-cron

- name: remove mask from networkd
  systemd_service:
    name: systemd-networkd
    masked: false

- name: purge network manager
  apt:
    name: network-manager
    state: absent

- name: remove armbian-netplan.yml
  file:
    path: /etc/netplan/armbian-default.yaml
    state: absent

##FIXME this should be conditional some people will want wifi one day
- name: purge other things i dont want
  apt:
    name: "{{ uninstall_package_list }}"
    state: absent
  vars:
    uninstall_package_list:
      - networkmanager-openvpn
      - openvpn
      - wpasupplicant
      - chrony

- name: check for armbian repo
  stat: 
    path: /etc/apt/sources.list.d/armbian.list
  register: stat_armbian_apt
  when: disable_armbian_apt_repo

## listen I love armbian, but it's just not safe to leave enabled
- name: friends dont let friends brick their router on kernel updates
  command: "mv /etc/apt/sources.list.d/armbian.list /etc/apt/sources.list.d/armbian.list.disabled"
  args:
    creates: /etc/apt/sources.list.d/armbian.list.disabled
  when:
    - stat_armbian_apt.stat.exists
    - disable_armbian_apt_repo

- name: harden ssh
  include_tasks: harden.yml
  tags:
    - harden
    - ssh

- name: armbian alternative optimizations
  include_tasks: alternative_optimizations.yml
  when:
    - enable_armbian_alternative_optimizations
  tags:
    - optimize 
