---
- name: generate foomuuri.conf
  template:
    src: foomuuri.conf.j2
    dest: "{{ foomuuri_conf_dir}}/foomuuri.conf"
    mode: '0600'
  notify:
    - validate foomuuri configuration 
    - reload foomuuri service

- name: generate zones.conf
  template:
    src: zones.conf.j2
    dest: "{{ foomuuri_conf_dir}}/zones.conf"
    mode: '0600'
  notify:
    - validate foomuuri configuration 
    - reload foomuuri service

- name: "assure {{ foomuuri_conf_dir }}/zone_policies.d dir exists"
  file:
    path: "{{ foomuuri_conf_dir }}/zone_policies.d"
    state: directory
    mode: '0700'

- name: generate zone policy files
  template:
    src: zone_policy.conf.j2
    dest: "{{ foomuuri_conf_dir}}/zone_policies.d/{{ item.key }}.conf"
    mode: '0600'
  loop: "{{ foomuuri_zone_policy | dict2items }}"
  notify:
    - validate foomuuri configuration 
    - reload foomuuri service
