- debug:
    msg: "{{ foomuuri_zone_map }}"

- debug: 
    msg: "{{ lookup('template', 'zone_policy.conf.j2') }}"
  loop: "{{ foomuuri_zone_policy | dict2items }}"

#- debug:
#    msg: "{{ item.key }} - {{ item.value.from_zone }}"
#  loop: "{{ foomuuri_zone_policy | dict2items }}"
