---
# tasks file for foomuuri

## debian pacakages only in sid or bookworm backports
- name: install packages
  apt:
    name: "{{ foomuuri_apt_packages }}"
    state: present

## we can hanve nice things
## https://github.com/FoobarOy/foomuuri/wiki

- name: generate configuration files
  include_tasks: configuration.yml
  tags:
    - foomuuri_config

- name: enable foomuuri service on startup
  systemd:
    name: foomuuri
    enabled: true
  when:
     - foomuuri_start_allowed is truthy(convert_bool=True)
  notify:
    - validate foomuuri configuration 
    - start foomuuri service

- name: Flush handlers to apply firewall settings now
  meta: flush_handlers
  tags:
    - foomuuri_config

