---
# tasks file for ansible-dnsmasq
- name: Alpine related tasks
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- name: Debian related tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL related tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: openSUSE related tasks
  ansible.builtin.include_tasks: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- name: Configure DNSMasq
  ansible.builtin.include_tasks: config_dnsmasq.yml
  tags:
    - dnsmasq_config
  when: dnsmasq_config

- name: Manage systemd DNS
  ansible.builtin.include_tasks: systemd_resolved.yml
  when:
    - ansible_service_mgr == "systemd"
    - dnsmasq_systemd_resolved_disable
