---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure [FRR](https://frrouting.org/)
  role_name: frr
  namespace: mrlesmithjr

  license: MIT
  min_ansible_version: '7'

  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - '7'
        - '8'
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - networking
    - routing

dependencies: []
