---
# defaults file for foomuuri

foomuuri_apt_packages:
  - foomuuri
  - foomuuri-firewalld

foomuuri_conf_dir: "/etc/foomuuri"

# allow ansible to start firewall
foomuuri_start_allowed: no

foomuuri_networks:
  eth0:
    interface: eth0
    zone: public
  eth1:
    interface: eth1
    zone: internal
  eth2:
    interface: eth2
    zone: dmz
  eth3:
    interface: eth3
    zone: dmz

foomuuri_zone_map: "{{ foomuuri_networks | lanefu.clammy.interfaces_by_zone }}"

foomuuri_macros:
 - iperf3 tcp 5201
 - iperf3more tcp 5202

foomuuri_templates:
  outgoing_services:
    description: common outgoing services
    rules:
      - dhcp-server
      - domain
      - https
      - ntp
      - ping
      - ssh
  iot_services:
    description: common outgoing services
    rules:
      - mqtt
      - secure-mqtt

foomuuri_zone_policy:
  localhost:
    to_zone: 
      - any:
          description: permit local traffic on router to zones
          rules:
            - template outgoing_services
      - public:
          description: allow traffic to internet
          rules:
            - accept
  internal:
    to_zone:
      - any:
          description: allow more default services
          rules:
            - ping
            - dns
            - http
            - https
            - http-alt
      - public:
          description: allow traffic to internet
          rules:
            - accept
      - dmz:
          description: permit specific services to dmz
          rules:
            - template outgoing_services
            - reject log
  dmz:
    to_zone:
      - any:
          description: allow ping and dns
          rules:
            - ping
            - dns
      - public:
          description: allow traffic to internet
          rules:
            - accept
      - internal:
          description: permit dmz to access iot services on internal
          rules:
            - template iot_services
            - reject log
## make sure booleans are strings in yes/no format
foomuuri_config_log_rate: "1/second burst 3 packets"
foomuuri_config_log_input: "yes"
foomuuri_config_log_output: "yes"
foomuuri_config_log_forward: "yes"
foomuuri_config_log_rpfilter: "yes"
foomuuri_config_log_invalid: "no"
foomuuri_config_log_smurfs: "no"
foomuuri_config_log_level: "level info"
foomuuri_config_localhost_zone: localhost
foomuuri_config_dbus_zone: public
foomuuri_config_rpfilter: "no"  # yes is hard mode
foomuuri_config_counter: "no"
foomuuri_config_set_size: 65535
foomuuri_config_recursion_limit: 65535
foomuuri_config_dbus_firewalld: "no"
foomuuri_config_nft_bin: nft
