---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    privileged: True
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: instance2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    privileged: True
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/host.yml
      host_vars: inventory/host_vars/
verifier:
  name: ansible
