---
- name: Redhat(legacy) | Installing Pre-Reqs
  ansible.builtin.yum:
    name: ["iproute", "sudo", "which"]
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: Redhat(legacy) | Set url on frr version less than or equal to 4.1
  ansible.builtin.set_fact:
    frr_url_part: "{{ frr_release_date }}"
  when:
    - frr_version <= "4.1"

- name: Redhat(legacy) | Set url on frr version 5
  ansible.builtin.set_fact:
    frr_url_part: "001"
  when:
    - frr_version == "5.0.2"

- name: Redhat(legacy) | Set url on frr version 6
  ansible.builtin.set_fact:
    frr_url_part: "01"
  when:
    - frr_version >= "6"

- name: Redhat(legacy) | Set FRR package list to install
  ansible.builtin.set_fact:
    frr_rpms:
      [
        "{{ frr_package_url }}/frr-{{ frr_version }}-{{ frr_url_part }}.el7.centos.x86_64.rpm",
      ]
  become: true

- name: Redhat(legacy) | Set Python Tools package list to install
  ansible.builtin.set_fact:
    frr_package_deb: "{{ frr_package_url }}/frr-pythontools-{{ frr_version }}-{{ frr_url_part }}.el7.centos.x86_64.rpm"

- name: Redhat(legacy) | Combine FRR package list amd Python Tools package list
  ansible.builtin.set_fact:
    frr_rpms: "{{ frr_rpms }} + [ '{{ frr_package_deb }}' ]"

- name: Redhat(legacy) | Installing FRR packages
  ansible.builtin.yum:
    name: "{{ frr_rpms }}"
    state: present
  become: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  notify:
    - restart frr
