---
- name: System tuning | Managing ipv4 Forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_file: "{{ frr_sysctl_file | default(omit) }}"
    state: present
  become: true
  with_items:
    - net.ipv4.ip_forward
  when:
    - frr_ip_forwarding
  tags:
    - molecule-notest

- name: System tuning | Managing ipv6 Forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_file: "{{ frr_sysctl_file | default(omit) }}"
    state: present
  become: true
  with_items:
    - net.ipv6.conf.all.forwarding
  when:
    - frr_ipv6_forwarding
  tags:
    - molecule-notest
