---
- name: redhat | Installing DNSMasq
  ansible.builtin.yum:
    name: dnsmasq
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing DNSMasq
  ansible.builtin.dnf:
    name: dnsmasq
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Ensuring DNSMasq Service is Enabled and Started
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
  become: true
