---
dependency:
  name: galaxy
driver:
  name: docker

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        unbound_enable_service: false
        unbound_reloaded_state: "stopped"

platforms:
  - name: ansible-ubuntu-18-04-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-20-04-lts
    image: ubuntu:20.04
  - name: ansible-ubuntu-lts
    image: ubuntu:22.04
  - name: ansible-debian
    image: debian:latest
  - name: ansible-arch
    image: archlinux:base
    dockerfile: Dockerfile.arch.j2
    command: /usr/lib/systemd/systemd
    privileged: true
  - name: ansible-almalinux
    image: almalinux:latest
    command: /usr/lib/systemd/systemd
    privileged: true
  - name: ansible-fedora
    image: fedora:38
    dockerfile: Dockerfile.fedora.j2
    privileged: true
    command: /usr/lib/systemd/systemd

scenario:
  name: default
verifier:
  name: ansible
role_name_check: 1
